# Generated by Django 5.2.13 on 2026-05-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "telegram_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Telegram ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
            },
        ),
        migrations.CreateModel(
            name="SourceMessage",
            fields=[
                (
                    "msg_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID сообщения"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(max_length=255, verbose_name="Отправитель"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                ("photos", models.JSONField(default=list, verbose_name="Фото")),
            ],
            options={
                "verbose_name": "Исходное сообщение",
                "verbose_name_plural": "Исходные сообщения",
                "ordering": ["date", "msg_id"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("running", "Бег"),
                            ("skiing", "Лыжи"),
                            ("cycling", "Велосипед"),
                            ("swimming", "Плавание"),
                            ("hiking", "Пеший поход"),
                        ],
                        max_length=32,
                        verbose_name="Активность",
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Расстояние (км)"
                    ),
                ),
                (
                    "pace_min_per_km",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Темп (мин/км)"
                    ),
                ),
                (
                    "base_points",
                    models.IntegerField(default=0, verbose_name="Базовые очки"),
                ),
                (
                    "streak_bonus",
                    models.IntegerField(default=0, verbose_name="Бонус серии"),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="Итого очков"),
                ),
                (
                    "msg_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ID сообщения",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="challenge.athlete",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["athlete", "date"],
            },
        ),
    ]
