# Generated by Django 5.2.13 on 2026-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemessage',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
    ]
