# Generated by Django 5.2.13 on 2026-05-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phpbb_id", models.IntegerField("ID в phpBB", unique=True)),
                ("name", models.CharField("Название", max_length=255)),
                ("description", models.TextField("Описание", blank=True)),
                ("topic_count", models.IntegerField("Количество тем", default=0)),
                ("post_count", models.IntegerField("Количество сообщений", default=0)),
                (
                    "last_post_title",
                    models.CharField(
                        "Заголовок последнего поста", blank=True, max_length=255
                    ),
                ),
                (
                    "last_post_username",
                    models.CharField(
                        "Автор последнего поста", blank=True, max_length=255
                    ),
                ),
                (
                    "last_post_at",
                    models.DateTimeField(
                        "Дата последнего поста", blank=True, null=True
                    ),
                ),
                ("sort_order", models.IntegerField("Порядок сортировки", default=0)),
            ],
            options={
                "verbose_name": "Категория форума",
                "verbose_name_plural": "Категории форума",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SubForum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phpbb_id", models.IntegerField("ID в phpBB", unique=True)),
                ("phpbb_parent_id", models.IntegerField("ID родителя в phpBB")),
                ("name", models.CharField("Название", max_length=255)),
                ("description", models.TextField("Описание", blank=True)),
                ("topic_count", models.IntegerField("Количество тем", default=0)),
                ("post_count", models.IntegerField("Количество сообщений", default=0)),
                (
                    "last_post_title",
                    models.CharField(
                        "Заголовок последнего поста", blank=True, max_length=255
                    ),
                ),
                (
                    "last_post_username",
                    models.CharField(
                        "Автор последнего поста", blank=True, max_length=255
                    ),
                ),
                (
                    "last_post_at",
                    models.DateTimeField(
                        "Дата последнего поста", blank=True, null=True
                    ),
                ),
                ("sort_order", models.IntegerField("Порядок сортировки", default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subforums",
                        to="forum.forumcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подфорум",
                "verbose_name_plural": "Подфорумы",
                "ordering": ["sort_order"],
            },
        ),
    ]
