# Generated by Django 5.2.13 on 2026-05-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phpbb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('last_post_title', models.CharField(blank=True, max_length=255)),
                ('last_post_username', models.CharField(blank=True, max_length=255)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phpbb_id', models.IntegerField(unique=True)),
                ('phpbb_parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('last_post_title', models.CharField(blank=True, max_length=255)),
                ('last_post_username', models.CharField(blank=True, max_length=255)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subforums', to='forum.forumcategory')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
