# Generated by Django 5.2.13 on 2026-05-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_forumuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phpbb_id",
                    models.IntegerField(unique=True, verbose_name="ID в phpBB"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "post_count",
                    models.IntegerField(default=0, verbose_name="Количество сообщений"),
                ),
                (
                    "subforum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="forum.subforum",
                        verbose_name="Подфорум",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phpbb_id",
                    models.IntegerField(unique=True, verbose_name="ID в phpBB"),
                ),
                (
                    "author_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя автора"
                    ),
                ),
                ("text_bbcode", models.TextField(verbose_name="Текст (BBCode)")),
                ("text_html", models.TextField(verbose_name="Текст (HTML)")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="forum.forumuser",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="forum.topic",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["created_at"],
            },
        ),
    ]
